<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="edit.aspx.cs" Inherits="LAB3.Edit" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Update Course</title>
    <style>
        body {
            font-family: Roboto;
            font-size: 1.7em;
        }
        .btn { font-size: inherit; }

        .full-width { width: 100% }
    </style>
</head>
<body>
<form id="form1" runat="server">
    <div>
        <asp:Label runat="server" ID="lb_tot" Text="Total: "></asp:Label> <br />
        <asp:Button runat="server" Text="Add" ID="btn_add" OnClick="btn_add_OnClick" CssClass="btn"/>
        <asp:GridView runat="server" CssClass="full-width" ID="gw_display" AutoGenerateColumns="False" EnableViewState="False" BorderColor="peru" BorderWidth="1" CellPadding="3" Font-Names="Roboto" Font-Size="1.2em" AutoGenerateDeleteButton="True" OnRowDeleting="gw_display_OnRowDeleting">
            <SelectedRowStyle BackColor="crimson"></SelectedRowStyle>
            <RowStyle HorizontalAlign="Center"></RowStyle>
            <HeaderStyle BackColor="seashell"></HeaderStyle>
            <Columns>
                <asp:BoundField HeaderText="Roll ID" DataField="RollId"/>
                <asp:BoundField HeaderText="Name" DataField="Name"/>
            </Columns>
        </asp:GridView>
    </div>
</form>
</body>
</html>